Repository myroslav111/bestellung-service, pull requests merged in 2024-11, with the labels that each got.

#6 add enderungen im bestellungs prozess
  src/main/java/info/bestellungsservice/apothekebestellungservice/DeliveryCalculator.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/Main.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/ProduktList.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/Task.md
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/BestellService.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/drohne/Drohne.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/drohne/DroneOS.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/drohne/InfoCopter.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/UserFileManager.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/logistikzentrum/Logistikzentrum.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/logistikzentrum/Warenbestand.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/produkt/Produkt.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/AnzeigenBeleg.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerAnmeldeDatenAbfragen.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerUmfrage.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/Nachricht.java
Labels: enhancement

#12 Create README.md
  README.md
Labels: documentation

#20 #11 Refactoring: Namen und Texte refactored
  .idea/uiDesigner.xml
  src/main/java/info/bestellungsservice/Main.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/DeliveryCalculator.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/Main.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/ProduktList.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/Task.md
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/docs/Shortcuts.md
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/UserFileManager.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/logistikzentrum/Warenbestand.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/AbfrageAnmeldedaten.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/AnzeigenBeleg.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerAnmeldeDatenAbfragen.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerFragen.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerUmfrage.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/Nachricht.java
  src/main/resources/kunden.txt
Labels: enhancement

#23 #15: es wurde neue fun.(eine Paketinstanz erstellt und an das Logisti…
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/logistikzentrum/Logistikzentrum.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/resources/kunden.txt
Labels: enhancement

#22 #11: Refactoring Konsolen Übersicht (Rechtschreibung)
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/BenutzerFragen.java
Labels: refactoring

#21 #19: fix Userfrage email redundant
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
Labels: bug

#24 #20 Bugfix application runner
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/Main.java
  src/main/resources/kunden.txt
Labels: bug

#28 #21: builder patern implementierung für paket
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Builder.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/PaketBuilder.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/PaketBuilderInterface.java
Labels: enhancement

#29 #22: add. message klasse und kleine korektur für paket klasse + komen…
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/UserFileManager.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/PaketBuilder.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/PaketBuilderInterface.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/AbfrageAnmeldedaten.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/Nachricht.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/UserMessages.java
  src/main/resources/kunden.txt
Labels: enhancement

#32 #30: refac. der Apothekenklasse
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/BenutzerService.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Bestellverfahren.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/PaketVersandService.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/UserMessages.java
  src/main/resources/kunden.txt
Labels: refactoring

#33 SWEZAZUBI-2 Bessere Lösung für die Klasse Messages neue Enum wurde erstellt
  src/main/java/info/bestellungsservice/apothekebestellungservice/ApplicationRunner.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Apotheke.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/BenutzerService.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Bestellverfahren.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/apotheke/Warenkorb.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/enums/Farbcodes.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/enums/ProduktList.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/enums/UserMessagesText.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/Kunde.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/kunde/UserFileManager.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/logistikzentrum/Warenbestand.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/paket/Paket.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/AbfrageAnmeldedaten.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/Nachricht.java
  src/main/java/info/bestellungsservice/apothekebestellungservice/utils/UserMessages.java
  src/main/resources/kunden.txt
Labels: enhancement
